### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by yipingji** [Xiangxu-0103/SuperFlow#2]
Hi,

Thanks for amazing jobs!

I was just wondering if you plan to release codes

**Comment by Xiangxu-0103** [comment]
Thanks for your interest in our work. We are going to reorganize and release the code in the next month.

**Comment by Xiangxu-0103** [comment]
Hi @samy-ji, we are willing to inform you that the codes have already been released. Please let me know if you face any problems.
